CREATE TABLE PARTICIPANTES(cpf VARCHAR(10) PRIMARY KEY, nome VARCHAR(50), idquadrilha INT, foreign key(idquadrilha) references QUADRILHAS(IDQ)) ;
CREATE TABLE QUADRILHAS(idq int primary key , nome varchar(10), cpforganizador VARCHAR(10) );
CREATE TABLE APRESENTACOES(idquadrilha INT,datAA INT , hora INT, PRIMARY KEY(IDQUADRILHA,DATAA, HORA),FOREIGN KEY(IDQUADRILHA) REFERENCES QUADRILHAS(IDQ));
CREATE TABLE AVALIADORES(cpf VARCHAR(10) PRIMARY KEY, nome VARCHAR(50), FOREIGN KEY(CPF) REFERENCES PARTICIPANTES(CPF));
CREATE TABLE CRITERIOS(idc INT PRIMARY KEY, nome VARCHAR(50));
CREATE TABLE NOTAS(cpfavaliador VARCHAR(50), idquadrilha INT , idcriterio INT, nota INT , PRIMARY KEY(CPFAVALIADOR,IDQUADRILHA,IDCRITERIO),FOREIGN KEY(CPFAVALIADOR) REFERENCES AVALIADORES(CPF),
			FOREIGN KEY(IDQUADRILHA) REFERENCES QUADRILHAS(IDQ), FOREIGN KEY(IDCRITERIO) REFERENCES CRITERIOS(IDC)	  );


--2)
SELECT Q.NOME, MAX(N.NOTA)
FROM QUADRILHAS Q, NOTAS N
WHERE N.IDQUADRILHA = Q.IDQ AND N.IDCRITERIO = (SELECT DISTINCT C.IDC  FROM CRITERIOS C WHERE C.NOME = 'casamento junino')
GROUP BY Q.IDQ


--3)
SELECT Q.NOME
FROM QUADRILHAS Q, NOTAS N
WHERE Q.IDQ = N.IDQUADRILHA AND N.IDCRITERIO = (SELECT DISTINCT C.IDC FROM CRITERIOS C WHERE C.NOME = 'rainha do milho')
GROUP BY Q.IDQ
HAVING AVG(N.NOTA) > 7

--4)
SELECT AV.NOME
FROM AVALIADORES AV JOIN NOTAS NT ON AV.CPF = NT.CPFAVALIADOR
GROUP BY AV.CPF
HAVING NOT EXISTS (SELECT N.NOTA  FROM NOTAS N WHERE N.CPFAVALIADOR = AV.CPF AND N.NOTA < 7);

--5)
CREATE VIEW MEDIA AS
	SELECT CR.IDC , Q.NOME , AVG(NT.NOTA)
	FROM CRITERIOS CR, QUADRILHAS Q , NOTAS NT
	WHERE CR.IDC = NT.IDCRITERIO AND Q.IDQ = NT.IDQUADRILHA
	GROUP BY CR.IDC, Q.IDQ;

SELECT ME.IDC, ME.NOME
FROM MEDIA ME
WHERE ME.AVG = (SELECT MAX(MED.AVG) FROM MEDIA MED WHERE ME.IDC = MED.IDC GROUP BY MED.IDC );


--6)

SELECT DISTINCT Q.NOME
FROM QUADRILHAS Q
WHERE  10 = ANY(SELECT NT.NOTA FROM NOTAS NT,CRITERIOS CR WHERE NT.IDQUADRILHA = Q.IDQ AND CR.IDC = NT.IDCRITERIO AND CR.NOME = 'animação' )
EXCEPT
SELECT DISTINCT Q.NOME
FROM QUADRILHAS Q
WHERE 10 <> ANY(SELECT NT.NOTA FROM NOTAS NT, criterios cr WHERE NT.IDQUADRILHA = Q.IDQ and cr.idc = nt.idcriterio and cr.nome = 'música');

